Create entities
Tanzorr/passman pull request #1
Opened 2024-09-05 12:10 UTC by Tanzorr

2024-09-07 09:38 UTC, aharabara requested changes

2024-09-07 09:38 UTC, aharabara commented on .php-cs-fixer.cache
> +{"php":"8.3.10","version":"3.64.0:v3.64.0#58dd9c931c785a79739310aef5178928305ffa67","indent":"    ","lineEnding":"\n","rules":{"binary_operator_spaces":{"default":"at_least_single_space"},"blank_line
This file should be added to `.gitignore`. (remove it, commit the change, then add to gitignore)

2024-09-07 09:38 UTC, aharabara commented on app/Http/Controllers/PassowrdController.php
> +class PassowrdController extends Controller
Typo - `PassOwrd`

2024-09-07 09:38 UTC, aharabara commented on app/Models/Passowrd.php
> +class Passowrd extends Model
1. Model name typo (same as with controller)
2. Add phpdoc comments with a list of fields for this model
3. Add relations to `vault` and `sharedAccess` entities

2024-09-07 09:38 UTC, aharabara commented on app/Models/Passowrd.php
> +class Passowrd extends Model
You can find example here: https://laravel.com/docs/11.x/eloquent-relationships

2024-09-07 09:38 UTC, aharabara commented on app/Models/Passowrd.php
> +class Passowrd extends Model
Same things can be applied to other models

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121419_create_vaults_table.php
> +            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
this foreign key is not related to `user` table. Here is an ecample how to do it
```
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
 
Schema::table('posts', function (Blueprint $table) {
    $table->foreign('user_id')->references('id')->on('users');
});
```

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121419_create_vaults_table.php
> +            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
https://laravel.com/docs/11.x/migrations#foreign-key-constraints

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121419_create_vaults_table.php
> +            $table->boolean('is_shared')->default(false);
this flag is redundant - SharedAccess entity should decide if a pssword or a vault is shared with a specific user

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +            $table->foreignId('vault_id')->constrained()->cascadeOnDelete();
same thing as mentioned above,

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +        Schema::create('passowrds', function (Blueprint $table) {
passowrd != password

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +            $table->string('password');
better to name it `value`, because in code it will look like `$password->password` which is strange from semantical standpoint

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +        Schema::dropIfExists('passowrds');
typo

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->morphs('shareable');
relation should be named `shared` which related to `password` or `vault`. You also should define the relation in the model, take a look at this documentation - https://laravel.com/docs/11.x/eloquent-relationships#polymorphic-relationships

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->morphs('shareable');
don't forget you need a relation on the side of passwords and vaults too

2024-09-07 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->integer('access_level')->nullable();
what for is this field used?

2024-09-09 07:18 UTC, Tanzorr commented on .php-cs-fixer.cache
> +{"php":"8.3.10","version":"3.64.0:v3.64.0#58dd9c931c785a79739310aef5178928305ffa67","indent":"    ","lineEnding":"\n","rules":{"binary_operator_spaces":{"default":"at_least_single_space"},"blank_line
fixed

2024-09-09 07:18 UTC, Tanzorr commented on app/Http/Controllers/PassowrdController.php
> +class PassowrdController extends Controller
fixed

2024-09-10 17:36 UTC, Tanzorr commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +        Schema::create('passowrds', function (Blueprint $table) {
fixed

2024-09-10 17:37 UTC, Tanzorr commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +            $table->string('password');
added

2024-09-10 17:38 UTC, Tanzorr commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +        Schema::dropIfExists('passowrds');
fixed

2024-09-11 07:13 UTC, Tanzorr commented on database/migrations/2024_09_02_121419_create_vaults_table.php
> +            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
fixed

2024-09-11 07:15 UTC, Tanzorr commented on database/migrations/2024_09_02_121419_create_vaults_table.php
> +            $table->boolean('is_shared')->default(false);
is_shared removed

2024-09-11 16:52 UTC, Tanzorr commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->morphs('shareable');
added

2024-09-11 16:54 UTC, Tanzorr commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->integer('access_level')->nullable();
May it used for user access level?

2024-09-15 09:38 UTC, aharabara commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->integer('access_level')->nullable();
Change hte user_id relation to correct form, right now it relate to nothing. Seems that your migration for this clas looks ok, at least for now

2024-09-15 09:40 UTC, aharabara commented on app/Models/SharedAccess.php
> +    public function accessible(): MorphTo
name of the morph relation in migration and here are different (`shared` vs `accessible`)

2024-09-15 09:40 UTC, aharabara commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->integer('access_level')->nullable();
* change `shared` to `accessible`

2024-09-15 09:50 UTC, aharabara commented
Practices for next PR's (depends from company):
- the name of the branch should be in format of `<type>/<ticket-id>-<short_description>`,  
ex `feat/PS-16_create_password_entity`.
Possible types: feat, bugfix, hotfix, release
If your branch contains more tickets than initially was planned then commit each ticket related change with commit message in form of `PS-15 | Added controllers and migration for password entity.`
at the end when a squash commit is done you will have a formatted lisf of commits that will contain all tickets

2024-09-15 16:41 UTC, Tanzorr commented on database/migrations/2024_09_02_121433_create_passowrds_table.php
> +            $table->foreignId('vault_id')->constrained()->cascadeOnDelete();
fixed

2024-09-15 16:43 UTC, Tanzorr commented on database/migrations/2024_09_02_121533_create_shared_accesses_table.php
> +            $table->integer('access_level')->nullable();
fixed

2024-09-15 16:44 UTC, Tanzorr commented on app/Models/SharedAccess.php
> +    public function accessible(): MorphTo
now it the same

2024-09-16 07:17 UTC, merged